# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
title: Jekyll-base
description:
tagline:
url: localhost:4000

source: src
destination: serve
